jobs:
  include:
  - language: java
    jdk: openjdk11
    cache: 
      directories:
        - $HOME/.m2
    install: true
    script: mvn -B test  # mvn clean install would work, too

    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: P1y7nBNxKXRAfKveVx2gyRcd46qvv1lB6Mi59yS8JN3gsNKDWKGnodQeocJiPkC2irHpVHGTQq1vNZrNE91+HzEjuXKLGY2k2+S7TT5Z8vIqPpqg5zuc25VWzolxdl4Er45oEbQfPyqxmrHnxJw4djBz04yWITwKUWgDYBNDkU39uaJ3KgTewkUyWPjyXWGTxZkIHMKE//0q3/cjvX5uQtcFFEdP388jp+yvViWah/fA8mLGeHIrVoanFDSNWwR/Dg4t4wdvB9v2qhK3i2tPJk5ScFf7pYwuz0uUvstS4zHsVKe1zGcEsjV1b2LfgWNdLUoQnKiloHfPPOGMZ6njLmchGRG+8hrxcZqOt61sSFD/ZDCiv3cpXzmePMS/FXDUYepCp6MnvR7E0yGqyDYnvX77Fom44rWkZoop8iMNUFf+/OeJLcgomLvmIAv5kFEBYCo5t9IOYATFpFYJkhZvdHBmimcA6alrZuLjti/qcB8xwEfEDOg8tmjrROInkOu//ElmlXepSFsaHJtleOQInVmdND3Id3P7CZxKT4lR230LaGLxoxl8iOn5H5ERzkLbeaAywwsL/OHhDSu15JGnztTyO/Q4rVxEWZMHvMiC6jnJDr6YKLNdHGFGYK1eObzBXw4xzoWJ5Bg26zi9lxcXeng4ZyrWGXjtoJyrTBMYYjA=
      app: munkahelyi-nyilvantarto-rendsz
      on: master
