jobs:
  include:
  - language: java
    jdk: openjdk11
    cache: 
      directories:
        - $HOME/.m2
    install: true
    script: mvn -B test  # mvn clean install would work, too

    deploy:
      cleanup: false
      provider: heroku
      api_key:
        secure: ""
      app: munkahelyi-nyilvantarto-rendsz
    on: master
