jobs:
  include:
  - language: java
    jdk: openjdk8
    cache: 
      directories:
        - $HOME/.m2
    install: true
    script: mvn -B test  # mvn clean install would work, too

    #deploy:
    #  skip_cleanup: true
    #  provider: releases
    #  api_key: ""
    #  app: munkahelyi-nyilvantarto-rendsz
    #  on: main
